# 'jekyll serve'. If you change this file, please restart the server process.
  		  
  # Site settings		  # Site settings
 -title: Your awesome title		 +title: SUDDA
 -email: your-email@domain.com		 +email: support@sudda.info
  description: > # this means to ignore newlines until "baseurl:"		  description: > # this means to ignore newlines until "baseurl:"
 -  Write an awesome description for your new site here. You can edit this		 +  Suuda management solution for small business
    line in _config.yml. It will appear in your document head meta (for		    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.		    Google search results) and in your feed.xml site description.
  baseurl: "" # the subpath of your site, e.g. /blog		  baseurl: "" # the subpath of your site, e.g. /blog
 -url: "http://yourdomain.com" # the base hostname & protocol for your site		 +url: "http://sudda.info" # the base hostname & protocol for your site
 -twitter_username: jekyllrb		 +twitter_username: sudda
 -github_username:  jekyll		 +github_username:  sudda
  		  
  # Build settings		  # Build settings
  markdown: kramdown		  markdown: kramdown
