# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: G O S S I P A
email: #
description: > # this means to ignore newlines until "baseurl:"
  gossipa ඔබේ නිර්මාණ සහ අදහස් අපට එවන්න  
  
  
url: "http://gosspa.club" # the base hostname & protocol for your site
# twitter_username: 
# github_username:  
# baseurl: "" # the subpath of your site, e.g. /blog
# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
blog_name: කෑම පැයේ ලියන කතාව 
paginate: 2
paginate_path: "/blog/page:num/"
